language: node_js
node_js:
    - "6"
script:
    - cd demo-lib
    - npm install
    - npm run build
    - npm test
    - npm link
    - cd ../demo-app
    - npm link angular2-webpack-lib
    - npm install
    - npm test